# # Step1: Install tectonic & Import deps
# from langchain_core.tools import tool
# from datetime import datetime
# from pathlib import Path
# import subprocess
# import shutil

# @tool
# def render_latex_pdf(latex_content: str) -> str:
#     """Render a LaTeX document to PDF.

#     Args:
#         latex_content: The LaTeX document content as a string

#     Returns:
#         Path to the generated PDF document
#     """
#     if shutil.which("tectonic") is None:
#         raise RuntimeError(
#             "tectonic is not installed. Install it first on your system."
#         )

#     try:
#         # Step2: Create directory
#         output_dir = Path("output").absolute()
#         output_dir.mkdir(exist_ok=True)
#         # Step3: Setup filenames
#         timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
#         tex_filename = f"paper_{timestamp}.tex"
#         pdf_filename = f"paper_{timestamp}.pdf"
#         # Step4: Export as tex & pdf
#         tex_file = output_dir / tex_filename
#         tex_file.write_text(latex_content)

#         result = subprocess.run(
#                     ["tectonic", tex_filename, "--outdir", str(output_dir)],
#                     cwd=output_dir,
#                     capture_output=True,
#                     text=True,
#                 )

#         final_pdf = output_dir / pdf_filename
#         if not final_pdf.exists():
#             raise FileNotFoundError("PDF file was not generated")

#         print(f"Successfully generated PDF at {final_pdf}")
#         return str(final_pdf)

#     except Exception as e:
#         print(f"Error rendering LaTeX: {str(e)}")
#         raise

from langchain_core.tools import tool
from datetime import datetime
from pathlib import Path
import subprocess
import shutil
import logging

logger = logging.getLogger(__name__)


@tool
def render_latex_pdf(latex_content: str) -> dict:
    """
    Render a LaTeX document to PDF.

    Returns:
        {
            "success": True,
            "pdf_path": ".../paper_xxx.pdf"
        }
        OR
        {
            "success": False,
            "error": "error message",
            "stage": "latex_compilation"
        }
    """

    # ------------------------------
    # Check dependency
    # ------------------------------
    if shutil.which("tectonic") is None:
        logger.error("tectonic is not installed")
        return {
            "success": False,
            "error": "tectonic is not installed. Please install it.",
            "stage": "dependency_check"
        }

    try:
        logger.info("Rendering LaTeX to PDF using tectonic")

        # ------------------------------
        # Setup output directory
        # ------------------------------
        output_dir = Path("output").absolute()
        output_dir.mkdir(exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        tex_filename = f"paper_{timestamp}.tex"
        pdf_filename = f"paper_{timestamp}.pdf"

        tex_file = output_dir / tex_filename
        tex_file.write_text(latex_content, encoding="utf-8")

        # ------------------------------
        # Run tectonic
        # ------------------------------
        result = subprocess.run(
            ["tectonic", tex_filename, "--outdir", str(output_dir)],
            cwd=output_dir,
            capture_output=True,
            text=True,
        )

        # Log tectonic output for debugging
        if result.stdout:
            logger.info(result.stdout)
        if result.stderr:
            logger.error(result.stderr)

        final_pdf = output_dir / pdf_filename

        # ------------------------------
        # PDF not generated
        # ------------------------------
        if not final_pdf.exists():
            logger.error("PDF file was not generated by tectonic")

            return {
                "success": False,
                "error": "PDF file was not generated. LaTeX compilation failed.",
                "stage": "latex_compilation"
            }

        logger.info(f"Successfully generated PDF at {final_pdf}")

        return {
            "success": True,
            "pdf_path": str(final_pdf)
        }

    except Exception as e:
        # FULL traceback in terminal
        logger.exception("Unexpected error during LaTeX rendering")

        # Structured failure for agent (NO raise)
        return {
            "success": False,
            "error": str(e),
            "stage": "unexpected_exception"
        }
